### ISSUE TITLE
Issue with esnacc and ... (EXTENSIBILITY IMPLIED)

### ISSUE THREAD

**Issue by crw4096** [esnacc/esnacc-ng#7]
Hello,

Having trouble with ENUMERATED and "...".  According to X.680, clause 20.5 and 20.6, the type definition for `WontWork` below should be legal.  esnacc doesn't like the "..." .  Also, esnacc insists on having Enumerations all have a value, but that is minor in comparison to this.

Example code:

> ESnaccIssue DEFINITIONS ::= BEGIN
> 
> -- Works but is insufficient for my needs
> ThisWorks ::= ENUMERATED {
> 	  item0(0), item1(100)
> }
> 
> -- Must have this
> WontWork ::= ENUMERATED {
> 	 thing0(0), ..., thingN
> }
> 
> -- Having this would be great but not required
> AlsoWontWork ::= ENUMERATED {
> 	 alsoThing0, ..., alsoThingN
> }
> 
> END

Charles

**Comment by orgcandman** [comment]
This is definitely an issue - I will look at addressing this as I can.

**Comment by orgcandman** [comment]
Your "-- Must have this" example is not allowed by X.680 (see example one of 20.5, which is invalid because both thing0 and thingN will have the same value.

Otherwise, I may have something for you in an update. I won't make any statements about the extensibility portion, because I need to update both the C-lib and C++-lib to properly support it

**Comment by orgcandman** [comment]
Please see if the attached patch works for you (against current master)
[0001-yacc-Update-enumerations-definition.patch.txt](https://github.com/azsnacc/esnacc-ng/files/201183/0001-yacc-Update-enumerations-definition.patch.txt)
